### PR TITLE
Options grid update and cleanup

### PR DESCRIPTION
**Pull request by tiesont**
Added 'value' to options grid.

Also did a little cleanup on options grid to space out content a bit.

Added CSS rules to initially hide sub-navs on API sidebar.

### CODE REVIEW

**Comment by makeusabrew** [comment]
Sorry, been stacked out with work for the past few weeks. Only comment is the removal of the CNAME file - I don't want to be merging that! :)

**Comment by tiesont** [comment]
The CNAME bit should just be for my fork. The pages builder keeps trying to
use it when I push content, so I removed it.

**Comment by tarlepp** [comment]
You could always add that ```CNAME``` to .gitignore.

**Comment by tarlepp** [comment]
Also I'm not liking that you're adding same ```id``` attribute those ```<tr>``` elements, id should be unique. So on this case you should use ```class``` definition instead.

**Comment by tiesont** [comment]
Those IDs are for linking the sidebar nav, so I don't see how classes wold
be relevant. Am I missing something, otherwise?

On Mon, May 4, 2015 at 4:39 PM, Tarmo Leppänen <notifications@github.com>
wrote:

> Also I'm not liking that you're adding same id attribute those <tr>
> elements, id should be unique. So on this case you should use class
> definition instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makeusabrew/bootbox/pull/423#issuecomment-98844178>.
>



-- 
Tieson Trowbridge
Software Developer, Arivium Inc
arivium.com

**Comment by tarlepp** [comment]
@tiesont I was wrong, was looking this PR with my phone with a bit of hurry... Sorry for that wrong comment.

**Comment by tiesont** [comment]
@tarlepp No need to apologize, I just wanted to make sure I hadn't missed something obvious. I do need to get better at understanding Git; I thought the pull-request would only include what was committed at the time of the request, but it's obviously including bits like me removing the CNAME file from my fork, which happened afterwards...

@makeusabrew If it's easier, I can close/delete this pull request, do a fresh fork, and then commit the changes I intended to be part of the original pull request.

**Comment by makeusabrew** [comment]
@tiesont up to you; totally understand why you'd have deleted the CNAME file if GitHub was moaning at you, but as the PR stands merging it would break bootboxjs.com :cry: 

You can either revert that commit (`git revert 87304d3`) or as you say, go for a fresh fork. Whichever you prefer :)

**Comment by tiesont** [comment]
@makeusabrew Revert was probably the easiest option... :)

**Pull request closed without merging**
