### PR TITLE
Fixed to add headers only if the header option is set

### PR DESCRIPTION
**Pull request by Shotaro-Yoshinaga**
Currently, headers are always added even if no header options are set.

I fixed so that headers are only added when the header option is set.

### CODE REVIEW

**Comment by tiesont** [comment]
I believe I tried this originally, but the BS5 styles for the close button require the `.modal-header` element as a parent.

**Comment by Shotaro-Yoshinaga** [comment]
However, in my environment, a blank header is added even when the "title" option is not set.

**Comment by tiesont** [comment]
> However, in my environment, a blank header is added even when the "title" option is not set.

Yes, because **Bootstrap 5** requires a modal header for the close button to be styled correctly. Hence why an "empty" header is added - the close button is part of the header.

**Comment by Shotaro-Yoshinaga** [comment]
What if I don't need the close button?
In this case, we would like to avoid displaying a blank header.

**Comment by tiesont** [comment]
I should be accounting for that - the header is omitted if neither title nor close button would be rendered.

Github is slightly out of date with my working copy - I'll try to get that sync'd up tonight.

**Comment by Shotaro-Yoshinaga** [comment]
I appreciate very much for your kindness!
I am currently updating from BS3 to BS5 and am confused about the BS change...

**Comment by tiesont** [comment]
@Shotaro-Yoshinaga That's probably not making it any easier for you, either - the modal markup in BS5 is a lot closer to BS4, whereas BS3 requires a fair number of changes (we handle that internally already).

**Comment by Shotaro-Yoshinaga** [comment]
I was able to fix the showing/hiding of the modal, but the layout adjustment is not working now.
I am waiting for your update.

Thank you.

**Comment by tiesont** [comment]
Okay, I've pushed what I have to the WIP branch. You'll need to merge your local version in order to see the changes.

**Comment by Shotaro-Yoshinaga** [comment]
My colleague is not here today, I am unable to verify the impact of the features about our applications.
I will check next week and get back to you.

Thanks for responding today!

**Comment by Shotaro-Yoshinaga** [comment]
Sorry I'm late.
We have checked in our environment and the blank header is no longer displayed when the header option is not specified, so the problem is solved.

I appreciate very much for your kindness!

**Pull request closed without merging**
