### PR TITLE
Added code to throw an error when Bootstrap.js is not loaded

### PR DESCRIPTION
**Pull request by EvanCarroll**

### CODE REVIEW

**Comment by tarlepp** [comment]
I think that "better" approach is to check if bootstrap modal function is defined. Like ```if (typeof($.fn.modal) === 'undefined')```

**Comment by EvanCarroll** [comment]
Then we're not checking for version 3, which is a requirement. Perhaps the error message should say that though.

**Comment by makeusabrew** [comment]
I think the way this is already handled is sufficient. I don't think there's a big risk of mixups between V2 and V3 of Bootstrap.

**Comment by tarlepp** [comment]
I was thinking just custom bootstrap builds, where users can left modal handling out.

**Comment by makeusabrew** [comment]
Yeah; I agree :). That's what we already do: https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L593-L599

**Comment by EvanCarroll** [comment]
You don't do it, or it doesn't work -- because you can not have jQuery loaded /at all/ and the message I got was about `Bootbox.dialog` which led me to #298

**Comment by makeusabrew** [comment]
Sorry, it probably doesn't work because the code I referenced isn't actually released yet (hadn't realised). Unless you were already tracking the master branch - in which case then we definitely have an issue!

**Comment by EvanCarroll** [comment]
No, that would make sense. So long as I'm not crazy. You can close this. ;)

**Pull request closed without merging**
