### PR TITLE
Allow prompt to have "message" before the form

### PR DESCRIPTION
**Pull request by danilopolani**
About #543 

Note you'll need to add a style to create a margin between them.

**PS**: I wrapped "message" inside a `<div>`, just to have an element reference.

### CODE REVIEW

**Comment by tiesont** [comment]
As noted in Contributing, 

> If you've added new functionality, please include tests which validate its behaviour

**Comment by DaniloMeritocracy** [comment]
Can I just edit prompt.test.js adding a describe for "message" option?

**Comment by DaniloPolani** [comment]
Can I just edit prompt.test.js adding a describe for "message" option?

**Comment by tiesont** [comment]
> Can I just edit prompt.test.js adding a describe for "message" option?

@makeusabrew has final authority over that, but I would say no. @tarlepp?

**Pull request closed without merging**
