### PR TITLE
Bootstrap 5 support: Add new closeButton template

### PR DESCRIPTION
**Pull request by vladrusu**
Added support for Bootstrap 5's new close button html markup.
Also retained support for old BS versions.

### CODE REVIEW

**Comment by tiesont** [comment]
I'm not completely against this, but I'd have to see tests that verify that the correct button is rendered based on the version of Bootstrap used. That might be more than a little work, based on how the tests are setup.

**Comment by vladrusu** [comment]
@tiesont Isn't easier to just download a fresh copy of BS5 and see for yourself if it's rendered ok? :D

**Comment by tiesont** [comment]
That's not how we do things. There are tests that verify each feature works as intended.

**Comment by dleffler** [comment]
FWIW, the proper Bootstrap v5.0.2 button would be
```
'<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'

**Comment by tiesont** [comment]
Fixing this with a different method in v6. Closing.

**Pull request closed without merging**
