### PR TITLE
New "draggable" option to allow dialog to be dragged and dropped.

### PR DESCRIPTION
**Pull request by CGeorges**
Added a new option called draggable that allows users to drag and drop a.ny dialog with this option using HTML5 native functionality.

Demo:
 bootbox.dialog({
                    message: "I am a custom dialog",
                    title: "Custom title",
                    draggable: true,
                    backdrop:false
                });

### CODE REVIEW

**Comment by makeusabrew** [comment]
Hi @CGeorges,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. I'll try and look at this in detail and get back to you as soon as I can :).

Nick

**Comment by xabedamadev** [comment]
Hi, I have just download v. 4.4.0 but there is no draggable option. What should I do to have this option?? Thank you.

**Comment by tarlepp** [comment]
Hmm, I don't see support in Bootstrap modals for draggable? http://getbootstrap.com/javascript/#modals-options

**Comment by xabedamadev** [comment]
The first comment says: "Added a new option called draggable that allows users to drag and drop a.ny dialog with this option using HTML5 native functionality"

My question is: which is the version of bootbox that includes this functionality??

**Comment by tarlepp** [comment]
None, yet because this feature hasn't merged to main branch.

**Comment by xabedamadev** [comment]
Ok thank you, so I wait until the feature is merged.. Is it possible to know when??

**Comment by CGeorges** [comment]
I was hoping to receive an answer myself from @makeusabrew 

If there are any issues with my code I'd be happy to fix/update whatever it is.

**Comment by makeusabrew** [comment]
Sorry to have ignored this. I'm honestly not sure how I feel about it. Obviously at least two people (@CGeorges and @xabedamadev) feel like it would be of benefit but it's just not something which aligns with what Bootbox exists to do. The fact Bootstrap don't officially support it puts me off too.

Will have a think. Any other opinions welcome :)

**Comment by CGeorges** [comment]
If people wanted what official Bootstrap has to offer they wouldn't use Bootbox :) People come to bootbox when they need more features. 

A modularized version of Bootbox would be best I think, this way people can take Bootbox and easily add new extensions that will add multiple features. Similar to what datatables.net does  http://datatables.net/extensions/index

**Comment by tarlepp** [comment]
@CGeorges actually bootstrap just helps you make things easier, nothing extra that bootstrap modals cannot do by itself. I would make a PR to bootstrap repo to for that drag&drop and then when it's implemented there it should implemented with bootbox too.

**Comment by rfossella** [comment]
Hi.  It seems that the draggable feature is not available (and won't be?)  If so, can someone point me to an alternative?

**Comment by clintre** [comment]
The capability is there. I have done it for modals on my sites. Have not tried to incorporate it with Bootbox. However you can view it in action at http://jsfiddle.net/vacidesign/qaoxfptL/

**Pull request closed without merging**
