### PR TITLE
Documentation website revamp, revision 3

### PR DESCRIPTION
**Pull request by tiesont**
- Extracted content from home page into it's own page, Getting Started.
- Revamped examples page to show examples for each function.
- Corrected and expanded the Documentation page.

Also implemented a dark theme for the page headers. As before, a live version is available here: https://tiesontrowbridge.com/bootbox/

### CODE REVIEW

**Comment by makeusabrew** [comment]
Thanks man :).

The only issues are as discussed on twitter:

1) The Finch logo is weird, and very different to that on http://bootboxjs.com. There's nothing wrong with the entire Finch banner as it stands, it doesn't need reworking.
2) The footer content is wrong (old) too - again see the current site for the correct copy.
3) At the moment the branch can't be merged due to conflicts. Not had the time to check them out yet but something needs sorting... somewhere :).

Once these are sorted will merge ASAP.

**Comment by tiesont** [comment]
Updating 1) and 2). I think 3) is mostly due to cleaning up the markup, since I revamped the layout. I'll see if I can figure out where the conflicts are originating.

**Comment by tiesont** [comment]
Conflicts should be resolved at this point - the conflicts were entirely due to re-arranging some sections and doing a general cleanup on the previous markup.

**Comment by makeusabrew** [comment]
:heart:

**Comment by makeusabrew** [comment]
@tiesont thanks so much (again). Would you mind if I add you as a collaborator on this repo? I've had my head in the sand about it for far too long (work / life getting in the way) and noticed when triaging all the open issues yesterday you're very clued up about the project.

There'd be no expectation of commitment at all, but it'd be nice to add another individual to try and unblock things even just a tiny bit. Let me know :).

**Comment by tiesont** [comment]
@makeusabrew That's up to you. Fair warning, though: JavaScript isn't my best language, but I understand it well enough to be productive. Since I use Bootbox quite a bit in my projects, it just seems right to contribute back when possible.

**Comment by makeusabrew** [comment]
@tiesont that's absolutely fine. I'm not precious; but likewise if something's not quite right don't be offended if I change it around a bit. Honestly, any help is a big help, so thanks for everything so far :).

**Pull request merged**
