### PR TITLE
Russian says 'Apply' instead of 'Confirm'

### PR DESCRIPTION
**Pull request by Superpencil**
Russian says 'Apply' instead of 'Confirm', this fixes it 👍

### CODE REVIEW

**Comment by tarlepp** [comment]
@Superpencil tests are failing, so you need to make some changes to those too.

**Comment by Superpencil** [comment]
Thanks @tarlepp!

**Comment by tiesont** [comment]
@tarlepp Not sure if either of us has repo rights to do so, but there are a few locale updates like this that mean we really _should_ push a new release to 4.x. I started one a while back, but I'm not sure what all is involved in pushing that out, if I finish assembling it. Thoughts?

**Comment by tarlepp** [comment]
@tiesont I don't have rights to make that either :(

**Comment by Superpencil** [comment]
@makeusabrew can you give some rights to the most 1337 of these two?

**Pull request merged**
