### PR TITLE
Added Arabic locale

### PR DESCRIPTION
**Pull request by EmadOmar**
Arabic - ( ISO 639-1 : ar )
more: http://en.wikipedia.org/wiki/Arabic_language

### CODE REVIEW

**Comment by EmadOmar** [comment]
Sorry, I just realized that I need to include some tests too, according to the [contributing guidelines](https://github.com/makeusabrew/bootbox/blob/master/CONTRIBUTING.md).

Is there any example that I can follow to do the required tests?

**Comment by tarlepp** [comment]
Tests are fairly easy to add for locales, eg. https://github.com/makeusabrew/bootbox/blob/master/tests/locales.test.coffee#L367-L378

Add new tests and then you can run those on your own computer to make sure that everything works.

**Comment by EmadOmar** [comment]
@tarlepp Thanks for explanation. Now I have included the required tests.

**Comment by tarlepp** [comment]
@EmadOmar thanks for this!

**Comment by makeusabrew** [comment]
Thanks folks!

**Pull request merged**
