### PR TITLE
Adds Azerbaijani locale

### PR DESCRIPTION
**Pull request by irrevion**
Azerbaijani locale added

### CODE REVIEW

**Comment by tarlepp** [comment]
@irrevion ok, but if you're not providing tests for this we cannot approve your PR.

**Comment by tarlepp** [comment]
also main commit message is not saying anything else than "Update bootbox.js" which is bit weird...

**Comment by kounelios13** [comment]
How can we write tests?

**Comment by tarlepp** [comment]
simply running `npm test`

**Comment by tiesont** [comment]
@irrevion I will add the tests for you, so that we can get this merged in, but is there a reason Google thinks "Ləğv et" is "cancel" and "İmtina et" is "disclaim"? Do those values have a different connotation/meaning in Azerbaijani?

**Pull request merged**
