### PR TITLE
Bootstrap 5 modifications

### PR DESCRIPTION
**Pull request by bobrundle**
Changed close to btn-close and updated all the tests.

This code requires Bootstrap 5 now.  Won't work right for BS4 or earlier.  Would be nice to support earlier versions of bootstrap but don't see how.

### CODE REVIEW

**Comment by tiesont** [comment]
@bobrundle I appreciate the effort, but removing backward compatibility is a no-go for me. I'll leave this open until @tarlepp has a chance to weigh in, but I have no plans to merge this.

**Comment by jstark518** [comment]
@bobrundle Probably will have float issues with the close button when there is no title, Checkout my PR #798 .

**Comment by bobrundle** [comment]
Fair enough.  I'll look into the float issue.  I'll also work on BS3 and BS4 compatibility.

**Comment by jstark518** [comment]
> Fair enough. I'll look into the float issue. I'll also work on BS3 and BS4 compatibility.

Hopefully it works out, would be nice to be able to use this again.

**Comment by tarlepp** [comment]
BC brakes would need new major version, so I would not merge this one.

**Comment by tarlepp** [comment]
and really me and @tiesont don't really have the control of this repository - so we cannot make decisions like that, we're just trying to keep all working.

**Comment by jstark518** [comment]
> BC brakes would need new major version, so I would not merge this one.

I think he's going to fix that, would end off duplicating my PR but maybe he can do in a better way that gets merged?

**Comment by bobrundle** [comment]
> 

@jstark518 I look at your PR.  Very nice.  Does everything my PR hoped to do.  Tested it with BS3, BS4 and BS5.

**Pull request closed without merging**
